### ISSUE TITLE
Forge server won't start while playertrackingcompass is in mods folder

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#185] opened 2020-07-07 18:59 UTC
## **Information**
Minecraft version: 1.16.1
Forge version: 1.16.1-32.0.57
Environment: Multiplayer

Mod name: playertrackingcompass_1.16-1.2
Mod version: 1.2

## **Description**
Setting up server to use this mod. Have got collective (1.35) installed. Compass fully works in singleplayer.

Forge server will launch with **ONLY** Collective in mods folder, but as soon as I put in Compass it doesn't start.

## **Crash report**
[07Jul2020 19:36:23.210] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid playertrackingcompass
java.lang.RuntimeException: Failed to load hierarchy member net/minecraft/item/IItemPropertyGetter
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:86) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:35) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.lambda$visit$0(TransformerClassWriter.java:136) ~[modlauncher-5.1.0.jar:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_111]
	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:135) ~[modlauncher-5.1.0.jar:?]
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:340) ~[asm-tree-7.2.jar:7.2]
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:74) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformerClassWriter.<init>(TransformerClassWriter.java:48) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at com.natamus.playertrackingcompass.items.TrackingCompassItem.<init>(TrackingCompassItem.java:35) ~[?:1.0]
	at com.natamus.playertrackingcompass.Main.registerItems(Main.java:57) ~[?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_0_Main_registerItems_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:32.0]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_111]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) ~[?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:886) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:49) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:94) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forgeserver.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forgeserver.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forgeserver.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forgeserver.jar:?]
Caused by: java.io.IOException: Class not found
	at org.objectweb.asm.ClassReader.readStream(ClassReader.java:310) ~[asm-7.2.jar:7.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283) ~[asm-7.2.jar:7.2]
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:82) ~[modlauncher-5.1.0.jar:?]
	... 47 more
[07Jul2020 19:36:23.213] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found
[07Jul2020 19:36:23.214] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Player Tracking Compass (playertrackingcompass) encountered an error during the load_registries event phase
§7Failed to load hierarchy member net/minecraft/item/IItemPropertyGetter

**Comment by SinOverCos** [comment] 2020-08-09 18:47
My server refuses to start at all with this mod in the mods folder:

```
~> !!                                                                                                                                                                                                                                                                 [270/1850]
java -Xmx1G -Xms1G -jar forge-1.16.1-32.0.107.jar nogui
[03:35:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 32.0.107, --fml.mcpVersion, 20200625.160719, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, nogui]
[03:35:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 11.0.8 by Ubuntu
[03:35:09] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[03:35:09] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/usr/games/modded-mc/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=SERVER
[03:35:10] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[03:35:12] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[03:35:32] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 32.0.107, for MC 1.16.1 with MCP 20200625.160719
[03:35:32] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v32.0.107 Initialized
[03:35:33] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: net/minecraft/item/IItemPropertyGetter
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: com.natamus.playertrackingcompass.Main@5cde2659 registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NoClassDefFoundError: net/minecraft/item/IItemPropertyGetter
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:878)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.natamus.playertrackingcompass.items.TrackingCompassItem.<init>(TrackingCompassItem.java:35)
        at com.natamus.playertrackingcompass.Main.registerItems(Main.java:57)
        at net.minecraftforge.eventbus.ASMEventHandler_0_Main_registerItems_Register.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:110)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190)
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113)
        at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126)
        at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
        at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214)
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:870)
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206)
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:49)
        at net.minecraft.server.Main.main(Main.java:95)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
Caused by: java.lang.ClassNotFoundException: net.minecraft.item.IItemPropertyGetter

...

```

**Comment by Seyanthen** [comment] 2020-08-12 21:11
Same here, my server will not start with the playertrackingcompass_1.16-1.2.jar mod in the mods folder. All other mods I've tried work, and the collective-1.16.1-1.35.jar can be in the folder and its fine. Whenever the playertrackingcompass_1.16-1.2.jar is taken out of the folder, the server starts up just fine. I've tried re-installing my forge client and that did nothing to fix it. I'm kinda lost on what to do, and really hope that this issue can be resolved! I've included the latest log file for reference.
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/5065763/latest.log)

**Comment by Seyanthen** [comment] 2020-08-14 14:06
Okay, so it works fine and great while in 1.15.2, but really hope it could be a 1.16.1-2 thing because of the nether update. Just checking in on the thread, since there's been no activity...

**Comment by ricksouth** [comment] 2020-08-15 15:32
Hi everyone,

Thanks for the detailed logs. I've released a new version for 1.16.2 which should solve the issues you were having. I'll close the issue for now but please let me know if something is still wrong. Thanks again.

https://www.curseforge.com/minecraft/mc-mods/player-tracking-compass/files

**Closed as completed by ricksouth** 2020-08-15 15:32 UTC
Labels: Bug, Mod: Player Tracking Compass

**Comment by Seyanthen** [comment] 2020-08-15 20:43
So, I've got collective-1.16.2-1.37.jar and playertrackingcompass_1.16-1.2.jar in the client side mods folder, and those only. My forge client is 1.16.2-forge-33.0.5, when I click play, the launcher simply says "Error Game crashed: An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience." Sometimes it opens Minecraft for a second, but then it crashes. The game does actually launch with just collective in the mods folder. My dedicated server is running forge-1.16.2-33.0.5.jar, and when I run it by the .bat or by double clicking on forge-1.16.2-33.0.5.jar, it brings up the console window, but then it closes almost immediately. It has the same collective and playertrackingcompass .jar(s) in the mods folder. I included the latest.log, but I have no idea how to understand what it outputs, so I don't know what the issue is

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/5079441/latest.log)

A related question, can you /give a player a playertrackingcompass that has an nbt tag to track a specified player? Would it work with command blocks?

Thanks

**Comment by ricksouth** [comment] 2020-08-15 21:50
You need playertrackingcompass_1.16.2-1.3.jar silly! :)

Currently the tracking location is only saved on the client of the clicked player. If you need different behaviour feel free to open an issue with a description and I'll see what I can do

**Comment by Seyanthen** [comment] 2020-08-16 18:46
Ohhh! My bad, I downloaded the newest .jar but I must've mixed up files, thanks!
(It does work on my 1.16.2 server now)

**Comment by CounterSync** [comment] 2020-09-01 23:45
I'm experiencing the same problem, my Minecraft launcher will launch Forge 1.16.2 but wont actually get to the menu screen of Minecraft. I have playertrackingcompass_1.16.2-1.3.jar and Forge 1.16.2-forge-33.0.32

**Comment by James103** [comment] 2020-09-01 23:47
What crash files do you get?

**Comment by CounterSync** [comment] 2020-09-01 23:56
The error is a rendering overlay; java.lang.NullPointerException: Rendering overlay
I attached the crash file.
[crash-2020-09-02_08.29.06-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/5159291/crash-2020-09-02_08.29.06-client.txt)
