### ISSUE TITLE
Restrict giant spawns to specific dimensions

### ISSUE THREAD

**Issue by HatTrkPatrk** [Serilum/.issue-tracker#239] opened 2020-08-24 20:35 UTC
## **Information**
Mod name: Giant Spawn

## **Feature description**
Configure the mod to only spawn giant mobs in specific dimensions (by ID).

## **Example**
I have an alternate dimension on my server, let's say its dimension ID is 8999, that's set to use an amplified worldgen type (everything's ginormous). The giant spawns sound perfect for this environment, but not so much for the overworld in my case. Configure the mod to only spawn giants in dimID 8999 and voilà!

**Comment by James103** [comment] 2020-08-24 20:36
Related to (possible duplicate of) #227

**Comment by ricksouth** [comment] 2022-08-15 16:31
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Closed as not planned by ricksouth** 2022-08-15 16:31 UTC
Labels: Feature Request, Mod: Giant Spawn

**Comment by ricksouth** [comment] 2024-01-07 14:52
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
