### ISSUE TITLE
The Abyss: Chapter 2 Portal also being affected

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#549] opened 2021-04-21 02:31 UTC
Information:
Minecraft version: 1.16.5
Forge version: 36.1.0
Environment: Singleplayer (probably multiplayer too)

Version of Nether Portal Spread: 5.1

Mod name: The Abyss: Chapter II
Mod version: 1.9.7 - 1.16.5

Description:
The Abyss 2 mod portal, made with another portal block (unstable obsidian, from the abyss chapter II) is also being affected by the nether portal spread mod. For some reason it only triggers the spread on the portal once entering the abyss dimension trough that portal, spreading nether blocks both on the overworld and in the abyss dimension.

**Comment by Y3Z0N** [comment] 2021-04-29 22:38
This is not a bug. The Abyss 2 spread is a feature within implemented in the mod it self.

if the Abyss portal spreads nether blocks then its a bug caused by Nether Portal Spread. however i just wanted to let the dev know.

**Comment by anabsolutesloth** [comment] 2022-02-03 03:44
Bumping this, as i discovered Blue Skies' portals also trigger it.
Blue Skies' portals are extending Structure Gel API's `GelPortalBlock` class, which extends the vanilla `NetherPortalBlock` class, so this issue entirely comes down to if the mod is extending `NetherPortalBlock` or not.
Perhaps adding a Config option for a "Fuzzy Portal Detection" mode would be a way to alleviate this issue and allow a different degree of customization.

**Comment by ricksouth** [comment] 2024-02-29 18:10
Thank you for opening the issue and giving the mod a try! This has been fixed in version 8.0 of Nether Portal Spread. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/nether-portal-spread/files

**Closed as completed by ricksouth** 2024-02-29 18:10 UTC
Labels: Bug, Mod: Nether Portal Spread, Modloader: Forge
