### ISSUE TITLE
Spawning bees hangs server during Chunk Generation

### ISSUE THREAD

**Issue by lebagvondouche** [Serilum/.issue-tracker#626] opened 2021-07-21 14:25 UTC
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.61
Environment: Singleplayer / Multiplayer

Mod name: Realistic Bees
Mod version: 1.3

## **Description**
Server hangs during the spawning of bees on this line when chunk generating:

net.minecraftforge.eventbus.ASMEventHandler_1436_BeeEvent_onBeeSpawn_EntityJoinWorldEvent.invoke ()	147 399 ms (100 %)	0,0 ms (- %)

## **Crash report**
Since it's hanging there is no crash log but here is a thread dump:
https://gist.github.com/haeihaiehaei/e5ea70d514519cf4f8dd55a6995e93ab

Possible solution:
Use the following way of spawning instead:
https://github.com/TelepathicGrunt/Bumblezone/blob/ac90011db1771110826c6dc4d55c928741a8087c/src/main/java/com/telepathicgrunt/the_bumblezone/world/dimension/BzChunkGenerator.java#L624-L631

**Comment by James103** [comment] 2021-07-26 09:08
Possibly a duplicate of or related to #526

**Comment by ricksouth** [comment] 2021-08-07 16:14
Thanks for submitting the bug report! This has been fixed in Forge 36.1.51 on July 17th.

**Comment by ricksouth** [comment] 2021-08-07 16:32
Thanks for submitting the bug report! Fixed in version 1.5 of Realistic Bees.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files/all

**Closed as completed by ricksouth** 2021-08-07 16:32 UTC
Labels: Bug, Mod: Realistic Bees
