### ISSUE TITLE
Server crashes when player come near certain chunks in the nether

### ISSUE THREAD

**Issue by GiggySmalls** [Serilum/.issue-tracker#221] opened 2020-08-09 08:31 UTC
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.98
Environment: Multiplayer

Mod name: passiveendermen_1.16-1.1.jar
Mod version: 1.1

## **Description**
The server crashes when players reach certain chuncks in the nether. We added the mod after the server was in use for a few weeks. Every time a player get's close to certain chuncks (seem to be nether fortress related) the server crashes with passive enderman errors. We have set only prevent griefing to true. I had previously removed the faulty chunk to repair the server but it happened again in another chunk now. I have tested this in single player as well and came to the conclusion that without this mod the issue is not occurring and with the mod it always is.

We want to use the mod but if it makes everything crash we don't of course. Any help would be greatly appreciated!

## **Crash report**
[09Aug2020 10:20:34.306] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: com.natamus.passiveendermen.events.EndermenEvent@1aaa86bb onEndermanGriefing(Lnet/minecraftforge/event/entity/EntityMobGriefingEvent;)V
java.lang.NullPointerException
	at com.natamus.passiveendermen.events.EndermenEvent.onEndermanGriefing(EndermenEvent.java:28)
	at net.minecraftforge.eventbus.ASMEventHandler_80_EndermenEvent_onEndermanGriefing_EntityMobGriefingEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.event.ForgeEventFactory.getMobGriefingEvent(ForgeEventFactory.java:682)
	at net.minecraft.entity.projectile.FireballEntity.func_70227_a(FireballEntity.java:35)
	at net.minecraft.entity.projectile.DamagingProjectileEntity.func_70071_h_(DamagingProjectileEntity.java:73)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604)
	at net.minecraft.world.server.ServerWorld$$Lambda$5817/1019438324.accept(Unknown Source)
	at net.minecraft.world.World.func_217390_a(World.java:596)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:121)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at net.minecraft.server.MinecraftServer$$Lambda$5414/1479336745.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[09Aug2020 10:20:34.309] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:121) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5414/1479336745.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at com.natamus.passiveendermen.events.EndermenEvent.onEndermanGriefing(EndermenEvent.java:28) ~[?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_80_EndermenEvent_onEndermanGriefing_EntityMobGriefingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.getMobGriefingEvent(ForgeEventFactory.java:682) ~[?:?]
	at net.minecraft.entity.projectile.FireballEntity.func_70227_a(FireballEntity.java:35) ~[?:?]
	at net.minecraft.entity.projectile.DamagingProjectileEntity.func_70071_h_(DamagingProjectileEntity.java:73) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$5817/1019438324.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:596) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?]
	... 6 more

**Comment by ricksouth** [comment] 2020-08-15 16:50
Duplicate of #208 but thanks nonetheless for opening the issue and the detailed log! Should be fixed in version 1.2 of the mod.

**Closed as completed by ricksouth** 2020-08-15 16:50 UTC
Labels: Bug, Mod: Passive Endermen
