### ISSUE TITLE
NamedAreas not working on Multiplayer

### ISSUE THREAD

**Issue by jglunac** [Serilum/.issue-tracker#141] opened 2020-06-14 21:10 UTC
## **Information**

Minecraft version: 1.14.4
Forge version: forge-1.14.4-28.2.0
Environment:  Multiplayer

Mod name: Named Areas
Mod version: 3.8

## **Question**
I can use the mod perfectly on single player but in Multiplayer it will just not work, im a server owner, that means i have access to the FTP, I tried everything, even exporting my configuration from singleplayer, am I doing something wrong?

**Comment by ricksouth** [comment] 2020-06-15 06:36
Duplicate of #3

**Comment by ricksouth** [comment] 2020-06-15 06:38
I'm aware of the issue, sorry for the inconvenience. When I made the mod, I didn't know how to communicate in between the server and client.

I do now, and will completely rewrite the mod in the upcoming days/weeks. I've got a few things left on my todo list first though. Thanks for the interest!

**Closed as completed by ricksouth** 2020-06-15 06:38 UTC
Labels: Question, Mod: Named Areas

**Comment by ricksouth** [comment] 2020-06-24 19:03
Named Areas has been re-released as [Areas](https://www.curseforge.com/minecraft/mc-mods/areas). This is the initial version and I'll probably add more functionality to it in the future! The mod should be approved in a few hours. Would love to hear feedback, but multiplayer is finally a thing! :)

[https://www.curseforge.com/minecraft/mc-mods/areas](https://www.curseforge.com/minecraft/mc-mods/areas)
