### ISSUE TITLE
[Just Mob Heads] Modded mobs?

### ISSUE THREAD

**Issue by chimericdream** [Serilum/.issue-tracker#192] opened 2020-07-16 03:07 UTC
## **Information**
Mod name: Just Mob Heads

## **Feature description**
Would it be possible to add support for modded mob heads? Our modpack has a number of custom mobs, and it would be nice if we could get their heads added to loot tables as well.

Thanks!

**Comment by ricksouth** [comment] 2020-08-15 15:39
Duplicate of #160

**Closed as completed by ricksouth** 2020-08-15 15:39 UTC
Labels: Feature Request, Mod: Just Mob Heads
