### ISSUE TITLE
Perpetual "Saving World" Screen (The Vanilla Experience)

### ISSUE THREAD

**Issue by YoungFrick** [Serilum/.issue-tracker#220] opened 2020-08-08 12:10 UTC
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.69
Environment: Singleplayer

Mod name: The Vanilla Experience
Mod version: 2.5

## **Description**
So when I play in a singleplayer world, every so often (roughly every 10-15 minutes) The game changes suddenly and with no warning. I can't pick up items, when I break blocks no item drops, I can't kill mobs (passive or hostile) and I can't interact with anything with a GUI (crafting table, chest etc.) But when I click "save and exit" in the options menu, it is stuck on the "Saving World" screen, and if I press "Alt + F4" It is just stuck on a black screen. The only way to close the pack in the strange state is by killing the program through task manager. Sidenote: I am playing on the latest version of the pack, with nothing added or configured.

## **Crash report**
[2020-08-06-6.log.gz](https://github.com/ricksouth/serilum-mc-mods/files/5045222/2020-08-06-6.log.gz)

**Comment by ricksouth** [comment] 2020-10-09 10:23
I've updated quite a few mods in the pack, improved code and made them more efficient. I've just played the pack for an hour with 3G of RAM and haven't had any issues come up. I'm pretty certain the problem is fixed in thevanillaexperience_1.16.3-2.11. Thanks for letting me know and sorry for the inconvenience!

https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience

**Closed as completed by ricksouth** 2020-10-09 10:23 UTC
Labels: Modpack: The Vanilla Experience

**Comment by Firey34** [comment] 2021-06-18 19:26
I'm having the same issue with the current mod pack. After i left a nether portal. I would notice foxes and wolves nearby me, Just stop like statues. Can't hit them, push them. Nothing. I try to save and quit out of the world. Would be left sitting there for hours on end until i close the launcher out

**Comment by James103** [comment] 2021-06-19 06:26
Do you have the corresponding logs? If so, can you please post them here?

**Comment by Firey34** [comment] 2021-06-20 23:47
> the

I would but how do i do that?
