### ISSUE TITLE
Lockups on 1.16.1 Pack - 32.0.69

### ISSUE THREAD

**Issue by WHCTHBD** [Serilum/.issue-tracker#198] opened 2020-07-19 13:56 UTC
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.69
Environment: Singleplayer

Mod name: The Vanilla Experience [Modpack]
Mod version: 2.5

## **Description**
Downloaded as-is from Curse without any additional modifications. Game locks up on world creation and world loading, either gets in and shows a blank world or loads to a random x% and locks up. PC is well-specced for Minecraft, plenty of RAM allocated. 

## **Crash report**
Not available. Just locks up on loading.

**Comment by ricksouth** [comment] 2020-10-09 10:23
I've updated quite a few mods in the pack, improved code and made them more efficient. I've just played the pack for an hour with 3G of RAM and haven't had any issues come up. I'm pretty certain the problem is fixed in thevanillaexperience_1.16.3-2.11. Thanks for letting me know and sorry for the inconvenience!

https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience

**Closed as completed by ricksouth** 2020-10-09 10:23 UTC
Labels: Bug, Modpack: The Vanilla Experience
