### ISSUE TITLE
for fabric？

### ISSUE THREAD

**Issue by KawaiiTamako** [Serilum/.issue-tracker#265] opened 2020-09-13 15:15 UTC
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.15.2
for fabric？
Environment: Singleplayer 

Mod name: Mod
Mod version: x.x

## **Comment**
!

**Comment by James103** [comment] 2020-09-13 15:26
Related to / duplicate of #250, #219, and #183

Quoting from @ricksouth's earlier responses:
> All of my mods are for Forge, with no plans to port them to Fabric. Thanks for the interest though!

**Comment by ricksouth** [comment] 2020-10-03 00:01
Thanks for the interest, please check out the FAQ here:
https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ

**Closed as completed by ricksouth** 2020-10-03 00:01 UTC
Labels: Question
