### ISSUE TITLE
Cant break bedrock

### ISSUE THREAD

**Issue by Lughbaloo** [Serilum/.issue-tracker#399] opened 2021-01-31 18:08 UTC
## **Information**
Minecraft version: 1.16.4
Forge version: 1.16.4-35.1.36
Environment: Singleplayer & Multiplayer

Mod name: TNT Breaks Bedrock
Mod version: 1.2

## **Description**
TNT does not break bedrock as advertised. Only mods installed currently are collective and TNT breaks bedrock, and I am unable to break bedrock in either the overworld or the nether.

I've tested in both single player and multiplayer, alongside other mods and standalone. 

## **Crash report**
If available.

**Comment by ricksouth** [comment] 2021-02-07 16:25
I've just tested it and everything works as intended, both in the overworld and nether. I'm closing this issue for now, but if you've got more information from your console where it still doesn't work please open another one. It might say something about the mod being disabled.

For now I can't solve your problem. I'd suggest re-downloading everything and see if it's installed correctly. Thanks for the interest though!

**Closed as completed by ricksouth** 2021-02-07 16:25 UTC
Labels: Bug, Mod: TNT Breaks Bedrock

**Comment by Lughbaloo** [comment] 2021-02-08 00:44
I've just downloaded fresh versions in 1.16.5 and started a brand new world and this still does not break bedrock with tnt.

![image](https://user-images.githubusercontent.com/44557173/107164205-0115d000-697c-11eb-8e03-b9ee5a06cae1.png)

![image](https://user-images.githubusercontent.com/44557173/107164214-0bd06500-697c-11eb-8861-4df1cbb7fc4f.png)

![image](https://user-images.githubusercontent.com/44557173/107164220-112daf80-697c-11eb-8d9f-310d0abd0173.png)

![image](https://user-images.githubusercontent.com/44557173/107164231-2571ac80-697c-11eb-9e1d-8a88ce976cc0.png)

This is in single player. There are no extra mods as you can see. The world is brand new as you can also see. 

I've also attached the latest.log and latest debug.log
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/5940577/debug.log)

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/5940575/latest.log)

Not sure what to tell you sir. Everything is fresh installed.

**Comment by James103** [comment] 2021-02-08 00:50
What server hosting software did you set this up on? Does the result change if you instead setup the server on your own computer (or alt computer)?

**Comment by Lughbaloo** [comment] 2021-02-08 03:58
This is set up on my own computer. I've tested using both a server-client setup where I run a forge server using a bat file, and I've tried single player. The launcher is GDLauncher.

For the record, I have the latest version of Java 8 installed
![image](https://user-images.githubusercontent.com/44557173/107174615-ad65af80-6998-11eb-8189-6ac72c11d13d.png)
