### ISSUE TITLE
Deathbackup hasn't recorded a backup in 10 days.

### ISSUE THREAD

**Issue by judicius** [Serilum/.issue-tracker#567] opened 2021-05-06 03:07 UTC
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5
Forge version: 36.1.13
Environment: Multiplayer

Mod name: Death Backup
Mod version: x1.4

## **Question**
Mods installed and we just experienced a crash where a player lost everything not soulbound from the inventory. When we checked /deathbackup list there was nothing since 4/25  I don't see a setting that turns this off or on so i'm wondering if I'm missing something as to why the information is missing.

**Comment by ricksouth** [comment] 2022-09-17 15:53
I think the problem is, is that the deathbackup list works for the person issueing the command. It does not show all backups. Closing this for now, but please let me know if I'm wrong. Thanks for giving the mod a try!

**Closed as completed by ricksouth** 2022-09-17 15:53 UTC
Labels: Bug, Mod: Death Backup
