### ISSUE TITLE
[Configurable Despawn Timer] Breaks give command

### ISSUE THREAD

**Issue by jeremiahwinsley** [Serilum/.issue-tracker#348] opened 2020-12-25 04:07 UTC
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.13
Environment: Singleplayer 

Mod name: Configurable Despawn Timer
Mod version: 1.3

Mod name: Collective
Mod version: 1.53

## **Description**
This is on a fresh install with only these two mods. When using the give command, `/give @p minecraft:acacia_boat 1`, the command gives one item to the player and drops a phantom item on the ground.

**Comment by ZephyrWindSpirit** [comment] 2020-12-25 04:09
Can confirm this to be true, and with Rats installed, a tamed rat with the harvest command will pick up and put away the phantom item.

**Comment by James103** [comment] 2020-12-25 11:31
Is it that you can't reproduce this issue if the config is set to make items despawn in less than 5 minutes (as opposed to more than 5 minutes)? If so, then this is likely related to MinecraftForge/MinecraftForge#7481.

**Comment by ricksouth** [comment] 2021-02-11 11:48
Thanks for submitting the bug report! This has been fixed via a workaround in version 2.0 of the mod.

https://www.curseforge.com/minecraft/mc-mods/configurable-despawn-timer

**Closed as completed by ricksouth** 2021-02-11 11:48 UTC
Labels: Bug, Mod: Configurable Despawn Timer
