### ISSUE TITLE
Crash when drinking milk with Nutritious Milk (1.12)

### ISSUE THREAD

**Issue by vico93** [Serilum/.issue-tracker#49] opened 2020-03-17 22:46 UTC
I know 1.12.2 is quite old, but anyway i went to report here: whith Nutritious Milk (nm_1.12-1.0.jar) installed i got this crash when trying to drink a milk bucket.

[Relevant log](https://paste.dimdev.org/abonuzeceb.rb)

Using Forge 14.23.5.2847

Edit: i'm so idiot i forgot to add the proper label. Sorry.

**Comment by ricksouth** [comment] 2020-03-20 17:22
I've recompiled the mod on the latest 1.12 Forge version but it still uses the same function. What environment do you use (single/multiplayer)? Do other mods work as intended?

**Comment by vico93** [comment] 2020-03-22 09:00
I was playing on a dedicated server. All other mods worked fine

**Comment by MokahTGS** [comment] 2020-03-23 00:08
This is happening on 1.14.4 as well.

**Comment by ricksouth** [comment] 2020-04-10 12:25
Thanks for letting me know! It was a little tricky to find, but has been resolved in version 1.1 of the mod. It now works correctly both on single- and multiplayer.

[https://www.curseforge.com/minecraft/mc-mods/nutritious-milk](https://www.curseforge.com/minecraft/mc-mods/nutritious-milk)

**Closed as completed by ricksouth** 2020-04-10 12:25 UTC
Labels: Bug, Mod: Nutritious Milk
