### ISSUE TITLE
Chunks not loading on new world.

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#180] opened 2020-07-02 00:38 UTC
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.24
Environment: Singleplayer 

Mod name: The Vanilla Experience modpack
Mod version: 1.16-2.3

## **Description**
Created new world on the modpack and was stuck for couple minutes on chunkless world. 
Disabling villagespawnpoint removed the problem and worlds were created without issues.

**Comment by James103** [comment] 2020-08-15 16:59
Do you have any logs to share from successfully reproducing this?

It could be that there are no villages within 1.5 km (1500 blocks) of the world's origin and/or `/locate Village` was unable to find anything, hence world generation being stuck on choosing player spawn point.

**Comment by ricksouth** [comment] 2020-10-09 10:23
I've updated quite a few mods in the pack, improved code and made them more efficient. I've just played the pack for an hour with 3G of RAM and haven't had any issues come up. I'm pretty certain the problem is fixed in thevanillaexperience_1.16.3-2.11. Thanks for letting me know and sorry for the inconvenience!

https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience

**Closed as completed by ricksouth** 2020-10-09 10:23 UTC
Labels: Bug, Modpack: The Vanilla Experience
