### ISSUE TITLE
for fabric?

### ISSUE THREAD

**Issue by KawaiiTamako** [Serilum/.issue-tracker#381] opened 2021-01-17 14:14 UTC
## **Information**
(you can remove whatever is not applicable)
Minecraft version: xx.xx.xx
Forge version: xx.xx.xx
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Comment**
!
for fabric?

**Comment by James103** [comment] 2021-01-17 14:17
Duplicate of #219
See [the FAQ](https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ) for why the mods are Forge only for the time being.

**Closed as completed** 2021-01-25 13:26 UTC
Labels: Question
